"""
报告生成器
输出 Markdown + HTML 格式的测试报告
"""
import os
import json
import datetime
from jinja2 import Template
from config.settings import REPORT_DIR

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>SmartTest Agent — 测试报告</title>
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background:#0f172a; color:#e2e8f0; padding:40px 20px; }
    .container { max-width:1000px; margin:0 auto; }
    h1 { font-size:28px; color:#fff; margin-bottom:8px; }
    .subtitle { color:#94a3b8; font-size:14px; margin-bottom:24px; }
    .summary { display:flex; gap:20px; margin-bottom:32px; flex-wrap:wrap; }
    .stat { background:#1e293b; border-radius:12px; padding:20px 28px; min-width:120px; text-align:center; border:1px solid #334155; }
    .stat .num { font-size:36px; font-weight:700; }
    .stat .label { font-size:13px; color:#94a3b8; margin-top:4px; }
    .pass .num { color:#34d399; }
    .fail .num { color:#f87171; }
    .warn .num { color:#fbbf24; }
    table { width:100%; border-collapse:collapse; margin-top:16px; }
    th { text-align:left; padding:12px 16px; background:#1e293b; font-size:13px; color:#94a3b8; border-bottom:2px solid #334155; }
    td { padding:12px 16px; font-size:13px; border-bottom:1px solid #1e293b; }
    tr:hover td { background:rgba(59,130,246,0.05); }
    .badge { display:inline-block; padding:2px 8px; border-radius:4px; font-size:11px; font-weight:600; }
    .badge-pass { background:rgba(52,211,153,0.15); color:#34d399; }
    .badge-fail { background:rgba(248,113,113,0.15); color:#f87171; }
    .badge-cat { background:rgba(59,130,246,0.1); color:#60a5fa; }
    .issue { font-size:12px; color:#fbbf24; margin-top:4px; }
    .footer { margin-top:40px; padding-top:16px; border-top:1px solid #1e293b; color:#64748b; font-size:12px; }
  </style>
</head>
<body>
  <div class="container">
    <h1>SmartTest Agent — 测试报告</h1>
    <p class="subtitle">{{ api_title }} v{{ api_version }} | {{ endpoint_count }} 个端点 | {{ timestamp }}</p>

    <div class="summary">
      <div class="stat pass"><div class="num">{{ passed }}</div><div class="label">通过</div></div>
      <div class="stat fail"><div class="num">{{ failed }}</div><div class="label">失败</div></div>
      <div class="stat"><div class="num" style="color:#60a5fa">{{ total }}</div><div class="label">总用例</div></div>
      <div class="stat"><div class="num" style="color:#c084fc">{{ pass_rate }}%</div><div class="label">通过率</div></div>
      <div class="stat warn"><div class="num">{{ slow_count }}</div><div class="label">慢请求</div></div>
    </div>

    <table>
      <thead>
        <tr>
          <th>#</th>
          <th>用例名称</th>
          <th>分类</th>
          <th>方法</th>
          <th>状态码</th>
          <th>预期</th>
          <th>耗时</th>
          <th>结果</th>
        </tr>
      </thead>
      <tbody>
        {% for r in results %}
        <tr>
          <td>{{ loop.index }}</td>
          <td style="max-width:360px;word-break:break-all;">{{ r.case_name }}</td>
          <td><span class="badge badge-cat">{{ r.category }}</span></td>
          <td>{{ r.method }}</td>
          <td>{{ r.status_code }}</td>
          <td>{{ r.expected_status }}</td>
          <td>{{ r.elapsed_ms }}ms</td>
          <td>
            {% if r.passed %}
            <span class="badge badge-pass">通过</span>
            {% else %}
            <span class="badge badge-fail">失败</span>
            {% endif %}
            {% if r.validation_issues %}
            {% for issue in r.validation_issues %}
            <div class="issue">{{ issue.detail }}</div>
            {% endfor %}
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="footer">
      Generated by SmartTest Agent · {{ timestamp }}
    </div>
  </div>
</body>
</html>"""


class ReportGenerator:

    def __init__(self):
        os.makedirs(REPORT_DIR, exist_ok=True)

    def generate(self, results: list[dict], api_info: dict) -> dict:
        """
        生成 Markdown + HTML 双份报告
        返回: {"markdown_path": "...", "html_path": "..."}
        """
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        base_name = f"test_report_{timestamp}"
        md_path = os.path.join(REPORT_DIR, f"{base_name}.md")
        html_path = os.path.join(REPORT_DIR, f"{base_name}.html")

        # 统计数据
        total = len(results)
        passed = sum(1 for r in results if r["passed"])
        failed = total - passed
        pass_rate = round(passed / total * 100, 1) if total > 0 else 0
        slow_count = sum(1 for r in results if r.get("elapsed_ms", 0) > 5000)
        avg_elapsed = round(sum(r.get("elapsed_ms", 0) for r in results) / total) if total > 0 else 0

        # 按分类统计
        cat_stats = {}
        for r in results:
            cat = r.get("category", "其他")
            cat_stats.setdefault(cat, {"total": 0, "passed": 0})
            cat_stats[cat]["total"] += 1
            if r["passed"]:
                cat_stats[cat]["passed"] += 1

        # 生成 Markdown
        self._write_markdown(md_path, results, api_info, {
            "total": total, "passed": passed, "failed": failed,
            "pass_rate": pass_rate, "slow_count": slow_count,
            "avg_elapsed": avg_elapsed, "cat_stats": cat_stats,
            "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        })

        # 生成 HTML
        self._write_html(html_path, results, api_info, {
            "total": total, "passed": passed, "failed": failed,
            "pass_rate": pass_rate, "slow_count": slow_count,
            "timestamp": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        })

        return {"markdown_path": md_path, "html_path": html_path}

    def _write_markdown(self, path: str, results: list, info: dict, stats: dict):
        lines = [
            f"# SmartTest Agent — 测试报告",
            f"",
            f"**API**: {info.get('title', 'N/A')} v{info.get('version', 'N/A')}  ",
            f"**基地址**: {info.get('base_url', 'N/A')}  ",
            f"**端点数量**: {info.get('endpoint_count', 0)}  ",
            f"**生成时间**: {stats['timestamp']}  ",
            f"",
            f"## 概览",
            f"",
            f"| 指标 | 值 |",
            f"|------|-----|",
            f"| 总用例数 | {stats['total']} |",
            f"| 通过 | {stats['passed']} |",
            f"| 失败 | {stats['failed']} |",
            f"| 通过率 | {stats['pass_rate']}% |",
            f"| 慢请求 (>5s) | {stats['slow_count']} |",
            f"| 平均响应 | {stats['avg_elapsed']}ms |",
            f"",
            f"## 按分类统计",
            f"",
            f"| 分类 | 总数 | 通过 | 通过率 |",
            f"|------|------|------|--------|",
        ]
        for cat, cs in stats["cat_stats"].items():
            r = round(cs["passed"] / cs["total"] * 100, 1) if cs["total"] > 0 else 0
            lines.append(f"| {cat} | {cs['total']} | {cs['passed']} | {r}% |")

        lines += [
            f"",
            f"## 用例详情",
            f"",
            f"| # | 用例 | 分类 | 方法 | 状态码 | 预期 | 耗时 | 结果 |",
            f"|---|------|------|------|--------|------|------|------|",
        ]
        for i, r in enumerate(results, 1):
            status = "✅" if r["passed"] else "❌"
            lines.append(
                f"| {i} | {r['case_name'][:60]} | {r.get('category','')} | {r['method']} "
                f"| {r['status_code']} | {r['expected_status']} | {r.get('elapsed_ms',0)}ms | {status} |"
            )

        lines += [
            f"",
            f"---",
            f"*Generated by SmartTest Agent · {stats['timestamp']}*",
        ]

        with open(path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

    def _write_html(self, path: str, results: list, info: dict, stats: dict):
        template = Template(HTML_TEMPLATE)
        html = template.render(
            api_title=info.get("title", "N/A"),
            api_version=info.get("version", "N/A"),
            endpoint_count=info.get("endpoint_count", 0),
            timestamp=stats["timestamp"],
            total=stats["total"],
            passed=stats["passed"],
            failed=stats["failed"],
            pass_rate=stats["pass_rate"],
            slow_count=stats["slow_count"],
            results=results,
        )
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
